"""initial migration

Revision ID: 228affa40eea
Revises: 1db1e845d5fd
Create Date: 2015-11-30 10:59:29.430000

"""

# revision identifiers, used by Alembic.
revision = '228affa40eea'
down_revision = '1db1e845d5fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
