"""initial migration

Revision ID: 2ab98579664b
Revises: 3669c838963a
Create Date: 2015-11-25 20:19:09.394000

"""

# revision identifiers, used by Alembic.
revision = '2ab98579664b'
down_revision = '3669c838963a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
