"""initial migration

Revision ID: 3669c838963a
Revises: c1062934337
Create Date: 2015-11-25 19:25:46.592000

"""

# revision identifiers, used by Alembic.
revision = '3669c838963a'
down_revision = 'c1062934337'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
